require('config.colorscheme')
--require('config.completion')
require('config.galaxyline')
require('config.compe')
require('config.autopairs')
require('config.telescope')
require('config.nvimtree')
require('config.lspinstall')
